var definition = new Array("The process whereby a compact object such as a black hole or neutron star captures matter from a normal star or diffuse cloud.", 
"The central region of some galaxies that appears as an extremely luminous point-like source of radiation. They are powered by supermassive black holes accreting nearby matter.", 
"The process whereby a particle and its antimatter counterpart interact, converting their mass into energy according to Einstein’s famous formula E = mc2. For example, the annihilation of an electron and positron results in the emission of two gamma-ray photons, each with an energy of 511 keV.", 
"A system on a gamma-ray observatory that triggers when it detects an incoming charged particle (cosmic ray) so that the telescope will not mistake it for a gamma ray.", 
"A ^[A-Za-z ()]+ - .+form of matter identical to atomic matter, but with the opposite electric charge.", 
"One-sixtieth of a degree on the sky. Like latitude and longitude on Earth's surface, we measure positions on the sky in angles. A semicircle that extends up across the sky from the eastern horizon to the western horizon is 180 degrees. One degree, therefore, is not a very big angle. An arcminute is an even smaller angle, 1/60 as large as a degree. The Moon and Sun are each about half a degree across, or about 30 arcminutes. If you take a sharp pencil and hold it at arm's length, then the point of that pencil as seen from your eye is about 3 arcminutes across. ", 
"The scientific study of the Universe and objects beyond Earth, especially the positions, dimensions, distribution, motion, composition, energy, and evolution of celestial bodies and phenomena.", 
"A combination of physics and astronomy that deals principally with the physical processes of celestial bodies and phenomena. ", 
"Ground-based telescopes that indirectly detect very- high-energy gamma rays from space. These gamma rays interact with atoms in Earth’s atmosphere, producing Cherenkov Light.", 
"The smallest unit of an element which keeps the element's characteristics. An atom consists of one or more protons and neutrons (except for hydrogen, which may have no neutrons) in a nucleus, with one or more electrons outside the nucleus. ", 
"The Burst and Transient Source Experiment on board the Compton Gamma-ray Observatory. BATSE made all-sky observations of gamma-ray bursts and flares, as well as observing many other objects between 10 keV and 5 MeV.", 
"A theory of cosmology in which the Universe once existed in a hot, dense state, and has been expanding ever since. ", 
"Two stars that orbit around a common center of mass.", 
"An object with gravity so strong that nothing, not even light, can escape.", 
"A type of active galactic nucleus (AGN) that often appears as a point-like source of bright, highly variable radiation. Astronomers think blazars are AGN that have a jet of matter and radiation pointed directly at Earth.", 
"A detector that absorbs particles and photons, producing an electrical signal proportional to the total incident energy. It can be used to measure a gamma ray’s energy.", 
"Blue light emitted when particles travel through a medium faster than light travels through that medium.", 
"The Imaging Compton Telescope experiment on board the Compton Gamma-ray Observatory. COMPTEL detected gamma rays in the energy range 100 keV to 30 MeV.", 
"Material in which the pair-production process takes place. Due to conservation of momentum and energy, pair production cannot take place in empty space.", 
"Elementary particles or atomic nuclei that travel through interstellar space at speeds approaching that of light.", 
"The study of the origin, structure, and evolution of the Universe.", 
"A non-luminous gravitational component of the Universe invoked to explain the internal motions of galaxies and the motions of galaxies within clusters of galaxies.", 
"A unit of angular size. One degree is 1/360 of a full circle, or, conversely, there are 360 degrees in a circle. ", 
"The ratio between the mass of an object and its volume.", 
"Non-point-source gamma-ray emission from the plane of our Milky Way Galaxy. Mostly due to interactions of cosmic rays with interstellar material.", 
"Energetic Gamma Ray Experiment Telescope on board the Compton Gamma-ray Observatory. It operated from 30 MeV to 30 GeV.", 
"All the different wavelengths of light, which is also called electromagnetic radiation. Only a small portion of this spectrum is visible to the human eye. From lowest to highest energy, the broad energy bands within this spectrum are: radio, microwave, infrared, visible, ultraviolet, X rays, and gamma rays.", 
"An elementary particle with a single negative charge, and a mass of about 511 keV.", 
"A unit of energy, sufficient to excite atoms to emit visible light. (1 keV=1,000 eV, 1 MeV=1,000 keV, 1 GeV=1,000 MeV).", 
"Outside of, or beyond, our own Milky Way Galaxy.", 
"A measurement of the brightness of a source.", 
"A property of a wave that describes how many wave patterns or cycles pass by in a period of time. Frequency is often measured in Hertz (Hz), where a wave with a frequency of 1 Hz will pass by at 1 cycle per second.", 
"A component of our Universe made up of gas, a large number (usually more than a million) of stars, and dark matter. A galaxy is held together by gravity.", 
"A photon more energetic than an X ray (more than about 50 keV). Gamma rays are created from nuclear reactions or particle accelerations. Gamma rays are the most energetic photons of the electromagnetic spectrum.", 
"Einstein’s theory of gravity that unites special relativity, Newton’s laws of gravitation, and the insight that gravitational acceleration can be described by the curvature of space and time.", 
"Gamma-ray Large Area Space Telescope.", 
"The instrument on GLAST that is specifically designed to detect gamma-ray bursts.", 
"The attractive force of an object with mass on another object. The gravitational force between two objects depends on their masses and the distance between them.", 
"A theoretical faint glow of particles and radiation from a black hole, predicted by Stephen Hawking as a result of quantum-mechanical effects.", 
"The region of the electromagnetic spectrum with wavelengths in the range of 2.5 x 10-6 meters to 7 x 10-7 meters. Infrared photons are between visible-light photons and microwaves in the electromagnetic spectrum.", 
"Material or space between the stars.", 
"An atom or molecule that has lost or gained one or more electrons and has become electrically charged as a result.", 
"The process by which ions are produced, typically occurring by collisions with atoms or electrons, or by interaction with electromagnetic radiation.", 
"A collimated stream of relativistic particles and photons which flows from a central source (often a black hole).", 
"A temperature scale (named after Lord Kelvin) that measures an object's temperature above absolute zero, the theoretical coldest possible temperature. The temperature in Kelvins can be converted to Celsius by the equation K = 273 + C and to Fahrenheit by K = 273 + 5/9 * (F - 32).", 
"A unit of mass. One kilogram is defined as the mass of one liter (1,000 cubic centimeters) of water at 277 Kelvin. 1 kg = 2.2046 pounds.", 
"The primary science instrument on GLAST.", 
"Generally used to mean electromagnetic radiation that is visible to the human eye. Sometimes used to mean all wavelengths of electromagnetic radiation.", 
"The rate at which a star or other object emits energy, usually in the form of electromagnetic radiation.", 
"A neutron star with an extraordinarily powerful magnetic field. ", 
"The region of space around a magnetic body or a current-carrying body where objects can be affected by the magnetic forces due to the body or current.", 
"The immediate region around a body with a magnetic field where particle behavior is controlled by that field. ", 
"A measure of the total amount of material contained in a body.", 
"The fundamental international unit of length, defined as the length of the path traveled by light in vacuum during a period of 1/299,792,458 second. One meter is approximately 39.4 inches.", 
"The region of the electromagnetic spectrum with wavelengths in the range of 2.5 x 10-6 meters to 10-4 meters. Microwave photons are between infrared and radio in the electromagnetic spectrum.", 
"The name of our own Galaxy, which contains a flattened disk of stars about 100,000 light- years across, along with star clusters, interstellar gas and dust, and vast amounts of dark matter.", 
"The National Aeronautics and Space Administration, founded in 1958.", 
"A diffuse cloud of interstellar gas and dust.", 
"A particle commonly found in the nucleus of an atom with approximately the mass of a proton, but with zero electrical charge.", 
"An extremely dense core of a dead star that exploded as a supernovae. Neutron stars have diameters of about 20 kilometers and masses of about 1.5 times that of our Sun. A neutron star internally supports itself against gravity by pressure from the strong nuclear force between neutrons.", 
"The path of an object that is moving around a second object or point under the influence of gravity.", 
"Oriented Scintillation Spectrometer Experiment on board the Compton Gamma-ray Observatory (operated between 50 keV and 10 MeV).", 
"A physical process in which a gamma-ray photon transforms itself into a particle and its antimatter counterpart.", 
"The apparent motion of a relatively close object compared to a more distant background as the location of the observer changes. Astronomically, it is half the angle which a star appears to move as Earth moves from one side of the Sun to the other.", 
"Any machine or natural object that can accelerate charged particles, such as electrons, positrons, or protons to speeds approaching that of light.", 
"A device that produces electrical signals from faint pulses of light, using the photoelectric effect to produce a few electrons from incident light, then multiplying the number of electrons by a cascade process.", 
"The fundamental 'particle' of light. The energy of a photon is proportional to its frequency.", 
"A physical process in which a very-high-energy gamma-ray photon can borrow energy from an external source, such as a very strong magnetic field, and split into two lower-energy photons.", 
"An unstable nuclear particle with a rest mass between that of an electron and a proton. Also known as the pi meson.", 
"The antimatter counterpart of the electron, essentially an electron with a positive charge.", 
"A black hole that formed in the very early Universe from a dense concentration of matter. Primordial black holes have never been observed.", 
"A positively charged particle commonly found in the nucleus of an atom.", 
"A type of neutron star with a beam of emission that sweeps around as the star rotates.", 
"A cloud created from gas and particles blown off a neutron star.", 
"A short-lived change in the state of empty space due to quantum mechanics. Quantum fluctuations can often involve the rapid production and annihilation of virtual pairs of particles and their antimatter counterparts.", 
"Theories that attempt to merge Einstein’s general theory of relativity and quantum mechanics.", 
"The branch of physics dealing with the interactions of matter, energy, and space at tiny scales.", 
"A type of active galactic nucleus with a core that is extremely luminous in visible light and sometimes other wavelengths as well. ", 
"The process in which energy is emitted as electromagnetic waves, or the energy itself.", 
"The region of the electromagnetic spectrum with wavelengths longer than 10-4 meters. Radio photons have the lowest energies and longest wavelengths in the electromagnetic spectrum.", 
"A galaxy with strong radio emission, usually powered by an active galactic nucleus.", 
"The shift of spectral lines to longer wavelengths either due to the motion of the source away from the observer, the expansion of the Universe, or very strong gravity. ", 
"The size of the smallest detail visible in an image. Low resolution shows only large features, high resolution shows many small details.", 
"A natural or artificial body that revolves around a more massive body. For example, the Moon is a satellite of Earth. ", 
"The emission of light that occurs when electrons or positrons excite a substance in a transparent material they are passing through.", 
"A type of active galactic nucleus that is very luminous, but not as luminous as a quasar or blazar. ", 
"A compressional wave triggered by an explosion or energetic event.", 
"A burst-like emission of radiation and particles from a magnetic disturbance on the Sun.", 
"A unit of mass equivalent to the mass of the Sun: 1 solar mass = 2 x 1030 kilograms.", 
"Einstein’s theory of motion that relates mass and energy, and that states that no information can travel faster than the speed of light in a vacuum.", 
"A highly successful theory that describes three of the four known fundamental forces of nature and the elementary particles that make up all matter.", 
"A large ball of gas that creates and emits its own radiation through the process of nuclear fusion, or the core of star that once created and emitted its own radiation through fusion.", 
"A galaxy undergoing an intense round of star formation.", 
"A short-range but powerful nuclear force that operates within an atomic nucleus to hold protons together despite their positive electric charges.", 
"Particles that are smaller than an atom. Examples include the electron, proton, and neutron.", 
"An optical illusion in which material appears to be traveling faster than the speed of light.", 
"An extremely energetic and life-ending explosion of a star.", 
"The outwardly expanding outer portions of a star that exploded as a supernova and the expanding gaseous shell swept up by a supernova shock wave.", 
"An extension of the Standard Model of particle physics, supersymmetry hypothesizes the existence of a complete set of additional particles which complement those that are known to exist. Thus far, no supersymmetric particles have been detected. In some theories, the least massive supersymmetric particle (often called a WIMP) could be a good candidate for dark matter.", 
"A NASA satellite launched in 2004 that was specifically designed to study gamma-ray bursts.", 
"The part of a high-energy gamma-ray detector that is used to determine the trajectory of the incoming gamma-ray. For a silicon-strip detector-based tracker, the trajectories of electron-positron pairs are recorded. These pairs are produced by the converter.", 
"A source that appears and then disappears, such as a gamma-ray burst.", 
"The region of the electromagnetic spectrum with wavelengths in the range of 10-9 meters to 4 x 10-7 meters. Ultraviolet photons are between X rays and visible light in the electromagnetic spectrum.", 
"A space largely devoid of matter.", 
"The region of the electromagnetic spectrum seen by the human eye, with wavelengths in the range of 4 x 10-7 meters to 7 x 10-7 meters. Visible-light photons are between ultraviolet and infrared.", 
"The distance between the crest (or trough) on a wave and the crest (or trough) in the next cycle.", 
"The exposed core of a relatively low-mass star after it has ejected its atmosphere; it’s approximately the size of Earth but with the mass of our Sun. ", 
"Weakly Interacting Massive Particle; elementary particles predicted by supersymmetry but which have not been observed. WIMPS might comprise some or most of the Universe’s dark matter.", 
"The region of the electromagnetic spectrum with wavelengths in the range of 10-12 meters to 10-9 meters. X rays are between gamma rays and ultraviolet light in the electromagnetic spectrum.",
"Gas or liquid.",
"The International Space Station is a space station, or a habitable artificial satellite, in low Earth orbit.",
"Refers to metrics related to human characteristics.",
"Virtual Reality Laboratory NASA JSC",
"Is a spacecraft compartment containing a variety of support systems used for spacecraft operations.",
"An excercise machine that's equpped with an apparatus for measuring the work performed by excercizing.",
"An asteroid belt outside of the solar system",
"An interplanetary space probe that was launched as a part of NASA's New Frontiers program"
);