var word = new Array("Accretion", 
"Active galactic nuclei (AGN)", 
"Annihilation", 
"Anticoincidence Detector", 
"Antimatter", 
"Arcminute", 
"Astronomy", 
"Astrophysics", 
"Atmospheric Cherenkov Telescopes (ACTs)", 
"Atom", 
"BATSE", 
"Big Bang", 
"Binary stars", 
"Black hole", 
"Blazar", 
"Calorimeter", 
"Cherenkov light", 
"COMPTEL", 
"Converter", 
"Cosmic rays", 
"Cosmology", 
"Dark matter", 
"Degree", 
"Density", 
"Diffuse galactic emission", 
"EGRET", 
"Electromagnetic spectrum", 
"Electron", 
"Electronvolt (eV)", 
"Extragalactic", 
"Flux", 
"Frequency", 
"Galaxy", 
"Gamma ray", 
"General theory of relativity", 
"GLAST", 
"GLAST Burst Monitor (GBM)", 
"Gravity", 
"Hawking radiation", 
"Infrared", 
"Interstellar", 
"Ion", 
"Ionization", 
"Jet", 
"Kelvin (K)", 
"Kilogram (kg)", 
"Large Area Telescope (LAT)", 
"Light", 
"Luminosity", 
"Magnetar", 
"Magnetic field", 
"Magnetosphere", 
"Mass", 
"Meter (m)", 
"Microwave", 
"Milky Way", 
"NASA", 
"Nebula", 
"Neutron", 
"Neutron star", 
"Orbit", 
"OSSE", 
"Pair production", 
"Parallax", 
"Particle accelerator", 
"Photomultiplier tube", 
"Photon", 
"Photon splitting", 
"Pion", 
"Positron", 
"Primordial black hole", 
"Proton", 
"Pulsar", 
"Pulsar wind nebula", 
"Quantum fluctuations", 
"Quantum gravity", 
"Quantum mechanics", 
"Quasar", 
"Radiation", 
"Radio", 
"Radio galaxy", 
"Redshift", 
"Resolution", 
"Satellite", 
"Scintillation", 
"Seyfert galaxy", 
"Shock waves", 
"Solar flare", 
"Solar mass", 
"Special theory of relativity", 
"Standard Model of particle physics", 
"Star", 
"Starburst galaxy", 
"Strong nuclear force", 
"Subatomic particles", 
"Superluminal motion", 
"Supernova", 
"Supernova remnant", 
"Supersymmetry", 
"Swift", 
"Tracker", 
"Transient", 
"Ultraviolet", 
"Vacuum", 
"Visible light", 
"Wavelength", 
"White dwarf", 
"WIMP", 
"X ray",
"Fluid",
"ISS",
"Biometric",
"Dynamic Onboard Ubiquitous Graphic",
"Service Module",
"Ergometer",
"Kuiper belt",
"New Horizons"
);